export default function TermsPage() {
    return (
        <div className="min-h-screen bg-soft-bg">
            <main className="max-w-3xl mx-auto p-12 md:p-24 prose prose-slate">
                <h1>Terms of Service</h1>
                <p className="font-mono text-xs text-deep-charcoal/50">Last Update: January 2026</p>

                <h2>1. Services</h2>
                <p>UK Sourced Ltd provides Amazon account management, consulting, and wholesale distribution services. Specific deliverables are defined in individual service agreements.</p>

                <h2>2. AI Usage</h2>
                <p>Strategic advice generated by our AI tools (e.g., ASIN Audit) is for informational purposes only. UK Sourced Ltd is not liable for business decisions made solely on AI-generated recommendations.</p>

                <h2>3. Confidentiality</h2>
                <p>We adhere to strict confidentiality agreements regarding your proprietary product data and supply chains.</p>
            </main>
        </div>
    );
}
